language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

os:
  - linux

install:
  - pip3 install -r requirements.txt
  - pip3 install bandit

before_script:
  - bandit -c bandit.yml -r camille

script:
  - python3 setup.py test
